# Generated by Django 5.1.1 on 2024-09-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_event_delete_recruitmentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#3788d8', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
