# Generated by Django 5.1.1 on 2024-09-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_remove_event_content_remove_event_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='color',
            new_name='backgroundColor',
        ),
    ]
