# Generated by Django 5.1.1 on 2024-09-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_rename_color_event_backgroundcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='applyUrl',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
