# Generated by Django 5.1.1 on 2024-09-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTechnicalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_score', models.IntegerField(default=0)),
                ('attendance_score', models.IntegerField(default=0)),
                ('interview_score', models.IntegerField(default=0)),
                ('additional_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTechnicalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_score', models.IntegerField(default=0)),
                ('major_score', models.IntegerField(default=0)),
                ('attendance_score', models.IntegerField(default=0)),
                ('interview_score', models.IntegerField(default=0)),
                ('additional_score', models.IntegerField(default=0)),
            ],
        ),
    ]
